notifications:
  email: false

language: node_js

node_js:
- node

cache:
  directories:
  - node_modules

env:
  global:
  - BUILD_PATH=dist
  matrix:
  -
  - NODE_ENV=production PUBLIC_PATH=/sabor-website/
  - NODE_ENV=production PUBLIC_PATH=/cu/sabor/

addons:
  ssh_known_hosts:
  - "$DEPLOY_HOST"

before_script:
- openssl aes-256-cbc -k $ENCRYPTION_KEY -in .npmrc.enc -out .npmrc -d

script:
- npm run build

before_deploy:
- openssl aes-256-cbc -k $ENCRYPTION_KEY -in deploy_key.enc -out deploy_key -d
- eval "$(ssh-agent -s)"
- chmod 400 deploy_key
- ssh-add deploy_key

deploy:
- provider: pages
  local_dir: $BUILD_PATH
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
    condition:
    - $ENV = staging
- provider: script
  skip_cleanup: true
  script:
  - rsync -r --delete-after $BUILD_PATH $DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_PATH
  on:
    branch: production
    condition:
    - $ENV = production
