notifications:
  email: false

language: node_js

node_js:
- node

cache:
  directories:
  - node_modules

env:
- NODE_ENV="development"
- NODE_ENV="production" PUBLIC_PATH="/cu/sabor/"
- NODE_ENV="production" PUBLIC_PATH="/sabor-website/"

addons:
  ssh_known_hosts:
  - cunix.cc.columbia.edu

script:
- npm run build

before_deploy:
- openssl aes-256-cbc -K $encrypted_75ef2f069074_key -iv $encrypted_75ef2f069074_iv
  -in cunix_deploy_key.enc -out /tmp/cunix_deploy_key -d
- eval "$(ssh-agent -s)"
- chmod 400 /tmp/cunix_deploy_key
- ssh-add /tmp/cunix_deploy_key

deploy:

- provider: pages
  local_dir: dist
  skip_cleanup: true
  github_token: "$GITHUB_TOKEN"
  on:
    branch: master
    condition: 
    - $NODE_ENV = "production"
    - $PUBLIC_PATH = "/sabor-website/"

- provider: script
  skip_cleanup: true
  script:
  - rsync -r --delete-after dist/* $CUNIX_USER@cunix.cc.columbia.edu:/www/data/cu/sabor
  on:
    branch: production
    condition: 
    - $NODE_ENV = "production"
    - $PUBLIC_PATH = "/cu/sabor/"
