export const SHOW_MODAL = 'SHOW_MODAL'
export const CLOSE_MODAL = 'CLOSE_MODAL'
export const SET_MODAL_CONTENT = 'SET_MODAL_CONTENT'
export const SET_MODAL_TITLE = 'SET_MODAL_TITLE'
export const SET_MODAL_IMG_SRC = 'SET_MODAL_IMG_SRC'
export const SET_MODAL_INFO = 'SET_MODAL_INFO'
export const SET_MODAL_DESCRIPTION = 'SET_MODAL_DESCRIPTION'

export const ADD_EVENT = 'ADD_EVENT'
export const ADD_EVENTS = 'ADD_EVENTS'
export const SET_EVENTS = 'SET_EVENTS'

export const STORE = 'STORE'
